const mainAudioMusic = document.getElementById('main-audio-music');
const mainAudioSfxPrimary = document.getElementById('main-audio-sfx-primary');
const mainAudioSfxSecondary = document.getElementById('main-audio-sfx-secondary');
const mainAudioSfxTertiary = document.getElementById('main-audio-sfx-tertiary');
const menuHoverSfxSource = '../assets/sound/sfx/button_hover2.mp3';
const menuClickSfxSource = '../assets/sound/sfx/button_click.mp3';
const preloaderSfxSource = '../assets/sound/sfx/preloader.mp3';
let store = Redux.createStore(reducer);
let iframeid = document.getElementById('game-frame');
let preloaderContainerid = document.getElementById('preloader-containerid');
let preloaderLeftsideid = document.getElementById('preloader-leftsideid');
let preloaderRightsideid = document.getElementById('preloader-rightsideid');
let preloaderFakeBackgroundid = document.getElementById('preloader-fake-backgroundid');
let sfxHelper = 0;
let gameFrame;
let mainMenuArmorgamesImageid;
let mainMenuIronhideImageid;
let mainMenuStartImageid;
let mainMenuCreditsImageid;
let mainMenuCreditsButtonid;
let mainMenuStartButtonid;
let mainMenuArmorgamesButtonid;
let mainMenuIronhideButtonid;
let loadSavedMenuid;
let mainMenuPlayonmobileButtonid;
let mainMenuTwitterButtonid;
let mainMenuFacebookButtonid;
let mainMenuMusicButtonid;
let mainMenuSoundButtonid;
let loadSavedMenuCloseButtonid;
let creditsBackButtonid;
let loadSavedMenuLocalsaveHelpid;
let loadSavedMenuGameslot1Unusedid;
let loadSavedMenuGameslot1Usedid;
let loadSavedMenuGameslot2Unusedid;
let loadSavedMenuGameslot2Usedid;
let loadSavedMenuGameslot3Unusedid;
let loadSavedMenuGameslot3Usedid;
let loadSavedMenuGameslot1UsedHoverid;
let loadSavedMenuGameslot2UsedHoverid;
let loadSavedMenuGameslot3UsedHoverid;
let loadSavedMenuActionsContainerid;
let loadSavedMenuGameslot1Deleteid;
let loadSavedMenuGameslot2Deleteid;
let loadSavedMenuGameslot3Deleteid;
let loadSavedMenuGameslot1Delconfid;
let loadSavedMenuGameslot2Delconfid;
let loadSavedMenuGameslot3Delconfid;
let loadSavedMenuGameslot1Delconfyesid;
let loadSavedMenuGameslot1Delconfnoid;
let loadSavedMenuGameslot2Delconfyesid;
let loadSavedMenuGameslot2Delconfnoid;
let loadSavedMenuGameslot3Delconfyesid;
let loadSavedMenuGameslot3Delconfnoid;
let gameslot1Stars;
let gameslot1Shields;
let gameslot1Fists;
let gameslot2Stars;
let gameslot2Shields;
let gameslot2Fists;
let gameslot3Stars;
let gameslot3Shields;
let gameslot3Fists;
let savedData;
